### ISSUE TITLE
수박게임 공용 TODO

### ISSUE THREAD

**Issue by GHeeJeon** [my-ggott-games/my-ggott-games#3]
- [ ] Webstorm 설치
- [ ] 수박게임 오리지널 플레이해보기
- [ ] 수박게임 코드 클론(포크)하기
- [ ] 수박게임 제작의도(덕질, 기념일, 친목도모 등) 선정
- [ ] 이미지 고르기
- [ ] favicon 설정
- [ ] 사운드 변경

**Comment by GHeeJeon** [comment]
- [ ] 이미지 고르기
- [ ] 고른 이미지 편집하기

**Comment by GHeeJeon** [comment]
- [ ] 편집한 이미지 변환 후 추가하기
- [ ] 로컬에서 확인
- [ ] 언어 문제, 이미지 깨짐 등 프로토 타입 문제 해결하기

**Comment by GHeeJeon** [comment]
- [ ] 배포하기
- [ ] 서비스 보수 후 재배포하기(branch 활용)
